---
title: "Regime type and Economic Development"
author: "Abrar Trabulsi"
date: "11/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(haven)
library(readxl)
library(forcats)
library(gganimate)
library(naniar)
library(readr)
```
```{r Setting up my data}

# reading in my data where "mydata" is economic data from the Penn World Tables and my2data is data measuring democratic nature of countries from Polity V

mydata <- read_dta("/Users/abrartrabulsi/Downloads/pwt91.dta")
my2data <- read_xls("/Users/abrartrabulsi/Downloads/p4v2018.xls")

mydata[mydata == -88] <- NA

# this line of code replaces -88s with NAs which is the appropriate notation in R. -88 is registered as NA in other programs like Stata


# now we're making our Korea names the same so this merge works and I can actually run graphics and analysis on Korea.

newmydata <- mydata %>%
  mutate(country = fct_recode(country, "Korea South" = "Republic of Korea")) 
  
# merging my data. Use all = TRUE if you want to retain ALL columns from BOTH data sets

prepdata <- merge(newmydata, my2data, all = TRUE)

# dropping unnecessary variables (to be updated as I create my models)

newdata <- subset(prepdata, select = -c(cyear,ccode,scode))

# making a per capita GDP variable for my data

data <- newdata %>%
  mutate(gdpercap = rgdpna/pop)
```
```{r My Graphs}

# first I will map the Real GDP growth of the US, Singapore, and Korea from 1960-2018
  
data %>%
  filter(year > 1960) %>%
  ggplot(aes(x = year, y = rgdpna)) + 
  geom_line() +
  scale_y_log10() +
  labs(title = "", x = "Year", y = "Real GDP")

# next I will do the same but with regards to population

data %>%
  filter(year > 1960) %>%
  ggplot(aes(x = year, y = gdpercap)) + 
  geom_point() +
  transition_reveal(year) +
  scale_y_log10() +
  labs(title = "", x = "Year", y = "GDP Per Cap")

# I am doing this code in the RMD FIRST because it's easier to continuously work with, and change as needed before copying and pasting into the app.R file for plotly use.

```
```{r My Models}

# model displaying the relationship between Real GDP and Polity V score by year with population taken into account

mymap3 <- data %>%
  filter(country == "United States" | country == "Korea South" | country == "Singapore") %>%
  filter(year > 1960) %>%
  ggplot(aes(x = polity2, y = rgdpna, color = country)) + 
  geom_point() +
  geom_smooth(method = "lm", se = F) +
  facet_wrap(~ country) +
  theme(legend.position = "none") +
  scale_y_log10() +
  labs(title = "", x = "Polity V2 Score", y = "Real GDP")

# model displaying the relationship between GDP per capita and PolityV2 score by year with population taken into account

mymap4 <- data %>%
  filter(country == "Korea South" | country == "Singapore" | country == "Taiwan") %>%
  filter(year > 1960) %>%
  ggplot(aes(x = polity2, y = gdpercap, color = country)) + 
  geom_point() +
  annotate("rect", xmin = -10, xmax = 10, ymin = 1000, ymax = 4000, alpha = .1) +
  geom_hline(yintercept = 4000, linetype = "dotted", show.legend = TRUE) +
  geom_hline(yintercept = 1000, linetype = "dotted", show.legend = TRUE) +
  geom_hline(yintercept = 6000, color = "blue", show.legend = TRUE) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "red", show.legend = TRUE) +
  facet_wrap(~ country) +
  theme(legend.position = "right") +
  scale_y_log10() +
  labs(title = "", x = "Polity V2 Score", y = "Per Capita GDP")
```
```{r Writing In My Graphics} 

# writing in my graphics to the shiny app folder

write_rds(mymap1, "regime_vs_economic_shiny/mymap1.rds")
write_rds(mymap2, "regime_vs_economic_shiny/mymap2.rds")
write_rds(mymap3, "regime_vs_economic_shiny/mymap3.rds")
write_rds(mymap4, "regime_vs_economic_shiny/mymap4.rds")
write_rds(mymap5, "regime_vs_economic_shiny/mymap5.rds")
write_rds(mymap6, "regime_vs_economic_shiny/mymap6.rds")
```
```{r Function to turn a regression output into a ggplot}

# this is a function I found online which converts a regression output to a ggplot, it's extremely useful especially considering the fact that I don't know how to incorporate fixed effects into ggplot

ggplotRegression <- function (fit) {

require(ggplot2)

ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
  geom_point() +
  stat_smooth(method = "lm", col = "red") +
  labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                     "Intercept =",signif(fit$coef[[1]],5 ),
                     " Slope =",signif(fit$coef[[2]], 5),
                     " P =",signif(summary(fit)$coef[2,4], 5)))
}
```
```{r FE model for GDP}

# as.factor(variable) fixes for certain variables. This means these variables won't interfere with the overall regression. This is useful because certain anomalies like random financial meltdowns, cultural differences between countries etc won't affect the overall regression

m1 <- lm(rgdpna ~ polity2 + as.factor(country) + as.factor(year), data = data)
         summary(m1)
         
mymap5 <- ggplotRegression(m1) + labs(x = "Polity V2 Score", y = "GDP")
```
```{r FE model for GDP Per Capita}

# I am using GDP percapita due to the more specific analysis you can conduct with it

m2 <- lm(gdpercap ~ polity2 + as.factor(country) + as.factor(year), data = data)
         summary(m2)
         
mymap6 <- ggplotRegression(m2) + labs(x = "Polity V2 Score", y = "GDP Per Capita")
```
```{r Writing in my data into the shiny app folder}

# this is necessary to be able to make an interactive plot with Plotly

write_rds(data, "regime_vs_economic_shiny/data.rds")
```


